[package]
name = "xc3_test"
version = "0.5.0"
edition = "2021"

[dependencies]
xc3_lib = { path = "../xc3_lib" }
xc3_write = { path = "../xc3_write" }
xc3_model = { path = "../xc3_model" }
clap = { version = "4.2.7", features = ["derive"] }
rayon = "1.8.1"
globwalk = "0.9.1"
binrw = "0.13.3"
